import { Email, EmailEvent, EmailLink, ApiKey, Project, AnalyticsSummary, ActivityEvent, TopLink } from './types';

// Default Demo Project & API Key
export const DEMO_PROJECT: Project = {
  id: 'prj_demo_01',
  account_id: 'acc_demo_01',
  name: 'ERHA Technologies Outreach',
  description: 'Primary outbound sales and marketing emails',
  created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_API_KEYS: ApiKey[] = [
  {
    id: 'key_demo_01',
    project_id: DEMO_PROJECT.id,
    name: 'Apps Script Outbound Key',
    key_hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8', // SHA256 of ek_live_demo123456789
    key_prefix: 'ek_live_demo1...',
    last_used_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    revoked_at: null,
  },
];

// Seed Emails
export let DEMO_EMAILS: Email[] = [
  {
    id: 'em_01',
    project_id: DEMO_PROJECT.id,
    tracking_id: 'trk_01jxyz9876543210',
    message_id: '<msg-1001@apps-script.google.com>',
    recipient_email: 'client@example.com',
    recipient_name: 'Client',
    subject: 'Website Development Proposal',
    original_html: `<div><p>Hello Client,</p><p>Here is our proposal for your website development project.</p><p><a href="https://erhatechnologies.com/services">Our Services</a><br><a href="https://erhatechnologies.com/contact">Contact Us</a></p></div>`,
    tracked_html: `<div><p>Hello Client,</p><p>Here is our proposal for your website development project.</p><p><a href="http://localhost:3000/t/click/trk_01jxyz9876543210/lnk_01">Our Services</a><br><a href="http://localhost:3000/t/click/trk_01jxyz9876543210/lnk_02">Contact Us</a></p><img src="http://localhost:3000/t/open/trk_01jxyz9876543210" width="1" height="1" style="display:none;" /></div>`,
    sent_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    first_opened_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    last_opened_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    open_count: 4,
    click_count: 3,
    status: 'CLICKED',
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'em_02',
    project_id: DEMO_PROJECT.id,
    tracking_id: 'trk_02abcd1234567890',
    message_id: '<msg-1002@apps-script.google.com>',
    recipient_email: 'abc@gmail.com',
    recipient_name: 'Alex Johnson',
    subject: 'Follow-up: Cloud Migration Services',
    original_html: `<div><p>Hi Alex,</p><p>Check out our portfolio at <a href="https://erhatechnologies.com/portfolio">Portfolio</a>.</p></div>`,
    tracked_html: `<div><p>Hi Alex,</p><p>Check out our portfolio at <a href="http://localhost:3000/t/click/trk_02abcd1234567890/lnk_03">Portfolio</a>.</p><img src="http://localhost:3000/t/open/trk_02abcd1234567890" width="1" height="1" style="display:none;" /></div>`,
    sent_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    first_opened_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    last_opened_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    open_count: 1,
    click_count: 0,
    status: 'OPENED',
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'em_03',
    project_id: DEMO_PROJECT.id,
    tracking_id: 'trk_03efgh9876543210',
    message_id: '<msg-1003@apps-script.google.com>',
    recipient_email: 'sarah@designco.org',
    recipient_name: 'Sarah Connor',
    subject: 'Quarterly Security Audit & Compliance Overview',
    original_html: `<div><p>Hello Sarah,</p><p>Read our whitepaper <a href="https://erhatechnologies.com/whitepaper">Security Whitepaper</a>.</p></div>`,
    tracked_html: `<div><p>Hello Sarah,</p><p>Read our whitepaper <a href="http://localhost:3000/t/click/trk_03efgh9876543210/lnk_04">Security Whitepaper</a>.</p><img src="http://localhost:3000/t/open/trk_03efgh9876543210" width="1" height="1" style="display:none;" /></div>`,
    sent_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    first_opened_at: null,
    last_opened_at: null,
    open_count: 0,
    click_count: 0,
    status: 'SENT',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export let DEMO_EMAIL_LINKS: EmailLink[] = [
  {
    id: 'lnk_01',
    email_id: 'em_01',
    original_url: 'https://erhatechnologies.com/services',
    link_label: 'Our Services',
    link_index: 0,
    click_count: 2,
    first_clicked_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    last_clicked_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'lnk_02',
    email_id: 'em_01',
    original_url: 'https://erhatechnologies.com/contact',
    link_label: 'Contact Us',
    link_index: 1,
    click_count: 1,
    first_clicked_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    last_clicked_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'lnk_03',
    email_id: 'em_02',
    original_url: 'https://erhatechnologies.com/portfolio',
    link_label: 'Portfolio',
    link_index: 0,
    click_count: 0,
    first_clicked_at: null,
    last_clicked_at: null,
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'lnk_04',
    email_id: 'em_03',
    original_url: 'https://erhatechnologies.com/whitepaper',
    link_label: 'Security Whitepaper',
    link_index: 0,
    click_count: 0,
    first_clicked_at: null,
    last_clicked_at: null,
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

export let DEMO_EMAIL_EVENTS: EmailEvent[] = [
  {
    id: 'evt_01',
    email_id: 'em_01',
    link_id: null,
    event_type: 'SENT',
    occurred_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    ip_address: null,
    user_agent: null,
    referer: null,
    metadata: null,
  },
  {
    id: 'evt_02',
    email_id: 'em_01',
    link_id: null,
    event_type: 'OPEN',
    occurred_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    ip_address: '192.168.1.50',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    referer: 'https://mail.google.com/',
    metadata: { client: 'Gmail Desktop' },
  },
  {
    id: 'evt_03',
    email_id: 'em_01',
    link_id: 'lnk_01',
    event_type: 'CLICK',
    occurred_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    ip_address: '192.168.1.50',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    referer: null,
    metadata: { label: 'Our Services' },
  },
  {
    id: 'evt_04',
    email_id: 'em_01',
    link_id: 'lnk_02',
    event_type: 'CLICK',
    occurred_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    ip_address: '192.168.1.50',
    user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)',
    referer: null,
    metadata: { label: 'Contact Us' },
  },
  {
    id: 'evt_05',
    email_id: 'em_01',
    link_id: 'lnk_01',
    event_type: 'CLICK',
    occurred_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    ip_address: '192.168.1.50',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    referer: null,
    metadata: { label: 'Our Services' },
  },
];
